<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchresult</name>
   <tag></tag>
   <elementGuidId>b010c917-397f-4a1f-bdf0-a3d23eb20008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
